kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: enm-nfs-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels:
      purpose: nfs        
---
kind: Service
apiVersion: v1
metadata:
  name: enm-nfs-service
spec:
  selector:
    app: enm-nfs
  ports:
  - name: ftp
    protocol: TCP
    port: 21
    targetPort: 21
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enm-nfs-deployment
  labels:
    app: enm-nfs
spec:
  replicas: 1   
  selector:
    matchLabels:
      app: enm-nfs
  template:
    metadata:
      labels:
        app: enm-nfs
    spec:
      volumes:
      - name: enm-nfs-pv-storage
        persistentVolumeClaim:
          claimName: enm-nfs-pv-claim      
      containers:
      - name: enm-nfs
        image: enm_nfs:latest
        imagePullPolicy: Never        
        ports:
        - containerPort: 21 
        volumeMounts:
          - mountPath: "/home/ftpusers"
            name: enm-nfs-pv-storage  