kind: PersistentVolume
apiVersion: v1
metadata:
  name: corda-partyb-pv-volume
  labels:
    type: local
    purpose: partyb
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/ericmcevoy/cordapps/corda-enterprise-kubernetes/volumes/parties/partyB"