kind: PersistentVolume
apiVersion: v1
metadata:
  name: enm-notary-pv-volume
  labels:
    purpose: notary
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/ericmcevoy/cordapps/corda-enterprise-kubernetes/volumes/notary"