kind: PersistentVolume
apiVersion: v1
metadata:
  name: enm-netmap-pv-volume
  labels:
    purpose: netmap
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/ericmcevoy/cordapps/corda-enterprise-kubernetes/volumes/netmap"