kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: enm-identity-manager-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      purpose: identity-manager
---
kind: Service
apiVersion: v1
metadata:
  name: enm-identity-manager-service
spec:
  selector:
    app: enm-identity-manager
  ports:
    - name: default
      protocol: TCP
      port: 10000
      targetPort: 10000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enm-identity-manager-deployment
  labels:
    app: enm-identity-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enm-identity-manager
  template:
    metadata:
      labels:
        app: enm-identity-manager
    spec:
      volumes:
        - name: enm-identity-manager-pv-storage
          persistentVolumeClaim:
            claimName: enm-identity-manager-pv-claim
      containers:
        - name: enm-identity-manager
          image: enm_identity_manager:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 10000
          volumeMounts:
            - mountPath: "/opt/corda/identity-manager/persistent"
              name: enm-identity-manager-pv-storage
